INSERT INTO `SUBJECT`(`Name`, `HoursPerWeek`) VALUES ('Geography',3);
INSERT INTO `SUBJECT`(`Name`, `HoursPerWeek`) VALUES ('History',3);
INSERT INTO `SUBJECT`(`Name`, `HoursPerWeek`) VALUES ('Italian',6);
INSERT INTO `SUBJECT`(`Name`, `HoursPerWeek`) VALUES ('Mathematics',5);
INSERT INTO `SUBJECT`(`Name`, `HoursPerWeek`) VALUES ('Physics',4);
INSERT INTO `CLASS`(`Name`) VALUES ('1A');
INSERT INTO `USER`(`SSN`, `Name`, `Surname`, `Email`, `Password`, `UserType`, `AccountActivated`) VALUES ('PNCMSM75D20L219X', 'Massimiliano', 'Ponci', 'm.ponci@parent.esrmsystem.com', 'Massi75', 'PARENT', 1);
INSERT INTO `USER`(`SSN`, `Name`, `Surname`, `Email`, `Password`, `UserType`, `AccountActivated`) VALUES ('STLRRT66T06L219L', 'Roberto', 'Stelluti', 'r.stelluti@parent.esrmsystem.com', 'Roberto66', 'PARENT', 1);
INSERT INTO `USER`(`SSN`, `Name`, `Surname`, `Email`, `Password`, `UserType`, `AccountActivated`) VALUES ('MNDFPP68C16L219N', 'Filippo', 'Mandini', 'f.mandini@parent.esrmsystem.com', 'Filippo68', 'PARENT', 1);
INSERT INTO `USER`(`SSN`, `Name`, `Surname`, `Email`, `Password`, `UserType`, `AccountActivated`) VALUES ('FLCRRT77B43L219Q', 'Roberta', 'Filicaro', 'r.filicaro@parent.esrmsystem.com', 'Roberta77', 'PARENT', 1);
INSERT INTO `USER`(`SSN`, `Name`, `Surname`, `Email`, `Password`, `UserType`, `AccountActivated`) VALUES ('PLLMRT70E68L219Q', 'Marta', 'Pellegrino', 'm.pellegrino@parent.esrmsystem.com', 'Marta70', 'PARENT', 1);
INSERT INTO `USER`(`SSN`, `Name`, `Surname`, `Email`, `Password`, `UserType`, `AccountActivated`) VALUES ('LNGMRN58M51L219R', 'Marina', 'Longobardi', 'm.longobardi@esrmsystem.com', 'Marina58', 'TEACHER', 1);
INSERT INTO `USER`(`SSN`, `Name`, `Surname`, `Email`, `Password`, `UserType`, `AccountActivated`) VALUES ('FNLTRS72H50L219Z', 'Teresa', 'Fanelli', 't.fanelli@esrmsystem.com', 'Teresa72', 'TEACHER', 1);
INSERT INTO `CHILD`(`SSN`, `Name`, `Surname`, `SSNParent1`, `SSNParent2`, `Class`) VALUES ('PNCRCR02C13L219K', 'Riccardo', 'Ponci', 'PNCMSM75D20L219X', 'FLCRRT77B43L219Q', '1A');
INSERT INTO `CHILD`(`SSN`, `Name`, `Surname`, `SSNParent1`, `SSNParent2`, `Class`) VALUES ('MNDGPP04E14L219U', 'Giuseppe', 'Mandini', 'MNDFPP68C16L219N', 'PLLMRT70E68L219Q', '1A');
INSERT INTO `MARK`(`StudentSSN`, `SUBJECTID`, `Date`, `Class`, `Score`) VALUES ('PNCRCR02C13L219K', 1, '2019-11-04', '1A', 8.75);
INSERT INTO `MARK`(`StudentSSN`, `SUBJECTID`, `Date`, `Class`, `Score`) VALUES ('PNCRCR02C13L219K', 2, '2019-11-07', '1A', 6.5);
INSERT INTO `MARK`(`StudentSSN`, `SUBJECTID`, `Date`, `Class`, `Score`) VALUES ('PNCRCR02C13L219K', 3, '2019-11-07', '1A', 7.25);
INSERT INTO `MARK`(`StudentSSN`, `SUBJECTID`, `Date`, `Class`, `Score`) VALUES ('PNCRCR02C13L219K', 5, '2019-11-08', '1A', 6.75);
INSERT INTO `MARK`(`StudentSSN`, `SUBJECTID`, `Date`, `Class`, `Score`) VALUES ('PNCRCR02C13L219K', 4, '2019-11-11', '1A', 8);
